name: Apply ready label
on:
  issue_comment:
    types: [created]

jobs:
  apply-label:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'CI_UPDATE_Test_And_Coverage_Passed_So_Approved')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Ready for review']
            })
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(github.event.comment.body, 'CI_UPDATE_Coverage_Suite_Failed') }}
        with:
          labels: 'Ready for review'
